### ISSUE TITLE
Previous version package - HL2 OS – 10.0.18362.1056 

### ISSUE THREAD

**Issue by th3jvh** [MicrosoftDocs/Hololens#5] opened 2020-07-15 18:26 UTC
[Enter feedback here]
Hello, 

I'm looking for link to download HL2 OS – 10.0.18362.1056 so I can use Advanced Recovery Tool to roll back a Hololens 2 OS. In the Advanced Recovery tool instructions it notes to download the latest OS, which defeats the purpose. 

Please advise, 

jvh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dedee10f-ed03-2db2-6606-fdc546ac5308
* Version Independent ID: c9d023d1-17a5-e47a-ea5f-2c4d0c214632
* Content: [Update HoloLens](https://docs.microsoft.com/en-us/hololens/hololens-update-hololens)
* Content Source: [hololens/hololens-update-hololens.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-update-hololens.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by evmill** [comment] 2020-10-15 15:09
Hello, we currently do not have plans to include download links to older OS versions in the documentation at this time. If you believe you are blocked by by not having access to an older build please reach out to support with your use case and why you are blocked and they can either help you become unblocked or provide you with the older build.
Thank you.
Closing this issue as this is By Design.

**Closed by evmill** 2020-10-15 15:09 UTC
